use customer;
describe customer;
# total revenue generated by male vs.female
select gender ,sum(purchase_amount) as revenue from customer group by gender;
# customers used discount 
select customer_id, purchase_amount
from customer 
where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount) from customer);
 # top 5 products wiht the highest avg review rating
 select item_purchased, round(avg(review_rating),2) as "average product rating"
 from customer 
 group by item_purchased order by avg(review_rating )desc limit 5;
 #compare the avg purchase btw express and standrad shippings
 select shipping_type,
 round(avg(purchase_amount) ,2) from customer 
 where shipping_type in ('standard','express')
 group by shipping_type;
 # comparing non subscriber and subscriber avg spend 
 select subscription_status,
 count(customer_id) as total_customers,
 round(avg(purchase_amount) ,2) as avg_spend,
 round(sum(purchase_amount) ,2) as total_revenue
 from customer
 group by subscription_status
 order by total_revenue, avg_spend desc;
 # 5 highest products purchased with the discount 
select item_purchased,
round(100 * sum(case when discount_applied ='yes' then 1 else 0 end)/count(*) ,2 ) as discount_rate
from customer
group by item_purchased
order by discount_rate desc limit 5;
#segemt customers into new returing and loyal based on there purchased history
with customer_type as (
select customer_id , previous_purchases,
case
when previous_purchases = 1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal'
end as customer_segement 
from customer
)
select customer_segement, count(*) as "number of customers"
from customer_type
group by customer_segement;
 # top 3 most purchased product
 with item_counts as (
 select  category,
 item_purchased,
 count(customer_id) as total_orders,
 row_number() over(partition by category order by count(customer_id)desc) as item_rank
 from customer
 group by category , item_purchased 
 )
 select item_rank,category,item_purchased,total_orders
 from item_counts
 where item_rank <=3;
 # customers who are repeate buyers are also likely to subscribe
 select subscription_status,
 count(customer_id) as repeate_buyers
 from customer
 where previous_purchases > 5
 group by subscription_status;
 #revenue by the age group
 select age_group,
 sum(purchase_amount) as total_revenue
 from customer
 group by age_group
 order by total_revenue desc;
 